version: '3.8'

services:

  telegram-bot:
    container_name: telegram_bot_container
    build: .
    command: python3 telegram_bot/main.py
    restart: always
    depends_on:
      - redis
      - postgres
      - mongo
    links:
      - redis

  whatsapp-bot:
    container_name: whatsapp_bot_container
    build: .
    command: python3 whatsapp_bot/main.py
    restart: always
    depends_on:
      - postgres
      - redis
      - telegram-bot
      - mongo
    links:
      - postgres
      - redis
      - telegram-bot
      - mongo


  redis:
    image: redis:latest
    container_name: redis_container
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        redis-server /usr/local/etc/redis/redis.conf
      '
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data

  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data/

  mongo:
    container_name: mongo_container
    image: mongo:latest
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo_volume:/data/db

volumes:
  redis_volume:
  postgres_volume:
  mongo_volume: