version: '3.8'

services:

  telegram-bot:
    container_name: telegram_bot_container
    build: .
    command: python3 telegram_bot/main.py
    restart: always
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    volumes:
      - tool_images_volume:/usr/src/tool-repair-tg/src/tool_images/

  whatsapp-bot:
    container_name: whatsapp_bot_container
    build: .
    command: python3 whatsapp_bot/main.py
    restart: always
    depends_on:
      - postgres
      - redis
      - telegram-bot
    links:
      - postgres
      - redis
      - telegram-bot


  redis:
    image: redis:latest
    container_name: redis_container
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        redis-server /usr/local/etc/redis/redis.conf
      '
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data

  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data/

  celery-worker:
    container_name: celery_worker_container_tool_repair
    build: .
    command: celery -A tasks.celery_app:celery_app worker -E -l info
    restart: always
    depends_on:
      - redis
    links:
      - redis

  celery-beat:
    container_name: celery_beat_container_tool_repair
    build: .
    command: celery -A tasks.celery_app:celery_app beat -l info
    restart: always
    depends_on:
      - redis
      - celery-worker
    links:
      - redis
      - celery-worker

volumes:
  redis_volume:
  postgres_volume:
  tool_images_volume: